### ISSUE TITLE
Help system not working in LibO 6.1

### ISSUE THREAD

**Issue by callegar** [hanya/MRI#14]
The help system has been totally renewed in LibO 6.1. Now it works by opening help pages in the system web browser.  Unfortunately this new setup seems to break the help pages of MRI, which do not appear anymore neither in the "index" nor in the "contents" sections of the documentation.

**Comment by hanya** [comment]
Fixed on 1.3.4. Thank you.

**Comment by callegar** [comment]
Cannot install 1.3.4 in 6.1 that hangs. Installing with 6.0 and then using the same profile in 6.1 assures that MRI is there, but the help system still does not provide the MRI help pages. Please, consider reopening.
